//CREATE LAG LI TAGS *START*
let tagId = ["comment", "doctype", "a", "abbr", "acronym", "address", "applet", "area", "article", "aside", "audio", "b", "base", "basefont", "bdi", "bdo", "big", "blockquote", "body", "br", "button", "canvas", "caption", "center", "cite", "code", "col", "colegroup", "data", "datalist", "dd", "del", "details", "dfn", "dialog", "dir", "div", "dl", "dt", "em", "embed", "fieldset", "figcaption", "figure", "font", "footer", "form", "frame", "frameset", "h1", "head", "header", "hr", "html", "i", "iframe", "img", "input", "ins", "kbd", "label", "legend", "li", "link", "main", "map", "mark", "meta", "meter", "nav", "noframes", "noscript", "object", "ol", "optgroup", "option", "output", "p", "param", "picture", "pre", "progress", "q", "rp", "rt", "ruby", "s", "samp", "script", "section", "select", "small", "source", "span", "strike", "strong", "style", "sub", "summary", "sup", "svg", "table", "tbody", "td", "template", "textarea", "tfoot", "th", "thead", "time", "title", "tr", "track", "tt", "u", "ul", "var", "video", "wbr"]

const tagsUl = document.getElementById("tags")
for (let i = 0; i < 119; i++) {
    const createLi = document.createElement("li")
    createLi.setAttribute("id", tagId[i])
    createLi.classList.add("tag")
    createLi.textContent = tagId[i]
    tagsUl.append(createLi)
}
//CREATE LAG LI TAGS *END*
let tagDetailObj = {
    comment: ["commentAttr", "comment", "You can add comments to your HTML source by using the following;", "&lt;!-- Write your comments here --&gt;", " Note: Comments are not displayed by the browser, but they can help document your HTML source code.", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    doctype: ["doctypeAttr", "doctype", "All HTML documents must start with a <!DOCTYPE> declaration. The declaration is not an HTML tag. It is an \"information\" to the browser about what document type to expect.", "&lt;! DOCTYPE html&gt;", " Note: The &lt;!DOCTYPE&gt; declaration is NOT case sensitive.", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Untitled' src='https://codepen.io/onepagehtml/embed/NWLRWbW?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>  See the Pen <a href='https://codepen.io/onepagehtml/pen/NWLRWbW'>  Untitled</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)  on <a href='https://codepen.io'>CodePen</a>.</iframe>"],
    a: ["aAttr", "a", "The &lt;a&gt; tag defines a hyperlink, which is used to link from one page to another.", "&lt;a href='URL'>Text&lt;/a&gt;", " Note: If the <a> tag has no href attribute, it is only a placeholder for a hyperlink.<br>A linked page is normally displayed in the current browser window, unless you specify another target.", "download<br>href<br>hreflang<br>media<br>ping<br>referrerpolicy<br>rel<br>target<br>type<br>", "<iframe height='300' style='width: 100%;' scrolling='no' title='a ' src='https://codepen.io/onepagehtml/embed/QWVKWpj?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>  See the Pen <a href='https://codepen.io/onepagehtml/pen/QWVKWpj'>  a </a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)  on <a href='https://codepen.io'>CodePen</a>.</iframe>"],
    abbr: ["abbrAttr", "abbr", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe class='interactive is-tabbed-shorter-height' height='300vw' width='100%' src='https://interactive-examples.mdn.mozilla.net/pages/tabbed/abbr.html' title='MDN Web Docs Interactive Example' loading='lazy' data-readystate='complete'></iframe>"],
    acronym: ["acronymAttr", "acronym", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    address: ["addressAttr", "address", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    applet: ["appletAttr", "applet", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    area: ["areaAttr", "area", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    article: ["articleAttr", "article", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    aside: ["asideAttr", "aside", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    audio: ["audioAttr", "audio", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    b: ["bAttr", "b", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    base: ["baseAttr", "base", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    basefont: ["basefontAttr", "basefont", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    bdi: ["bdiAttr", "bdi", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    bdo: ["bdoAttr", "bdo", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    big: ["bigAttr", "big", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    blockquote: ["blockquoteAttr", "blockquote", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    body: ["bodyAttr", "body", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    br: ["brAttr", "br", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    button: ["buttonAttr", "button", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    canvas: ["canvasAttr", "canvas", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    caption: ["captionAttr", "caption", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    center: ["centerAttr", "center", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    cite: ["citeAttr", "cite", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    code: ["codeAttr", "code", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    col: ["colAttr", "col", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    colegroup: ["colegroupAttr", "colegroup", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    data: ["dataAttr", "data", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    datalist: ["datalistAttr", "datalist", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dd: ["ddAttr", "dd", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    del: ["delAttr", "del", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    details: ["detailsAttr", "details", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dfn: ["dfnAttr", "dfn", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dialog: ["dialogAttr", "dialog", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dir: ["dirAttr", "dir", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    div: ["divAttr", "div", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dl: ["dlAttr", "dl", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    dt: ["dtAttr", "dt", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    em: ["emAttr", "em", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    embed: ["embedAttr", "embed", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    fieldset: ["fieldsetAttr", "fieldset", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    figcaption: ["figcaptionAttr", "figcaption", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    figure: ["figureAttr", "figure", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    font: ["fontAttr", "font", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    footer: ["footerAttr", "footer", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    form: ["formAttr", "form", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    frame: ["frameAttr", "frame", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    frameset: ["framesetAttr", "frameset", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    h1: ["h1Attr", "h1", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    head: ["headAttr", "head", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    header: ["headerAttr", "header", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    hr: ["hrAttr", "hr", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    html: ["htmlAttr", "html", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    i: ["iAttr", "i", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    iframe: ["iframeAttr", "iframe", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    img: ["imgAttr", "img", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    input: ["inputAttr", "input", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    ins: ["insAttr", "ins", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    kbd: ["kbdAttr", "kbd", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    label: ["labelAttr", "label", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    legend: ["legendAttr", "legend", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    li: ["liAttr", "li", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    link: ["linkAttr", "link", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    main: ["mainAttr", "main", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    map: ["mapAttr", "map", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    mark: ["markAttr", "mark", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    meta: ["metaAttr", "meta", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    meter: ["meterAttr", "meter", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    nav: ["navAttr", "nav", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    noframes: ["noframesAttr", "noframes", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    noscript: ["noscriptAttr", "noscript", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    object: ["objectAttr", "object", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    ol: ["olAttr", "ol", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    optgroup: ["optgroupAttr", "optgroup", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    option: ["optionAttr", "option", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    output: ["outputAttr", "output", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    p: ["pAttr", "p", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    param: ["paramAttr", "param", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    picture: ["pictureAttr", "picture", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    pre: ["preAttr", "pre", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    progress: ["progressAttr", "progress", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    q: ["qAttr", "q", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    rp: ["rpAttr", "rp", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    rt: ["rtAttr", "rt", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    ruby: ["rubyAttr", "ruby", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    s: ["sAttr", "s", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    samp: ["sampAttr", "samp", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    script: ["scriptAttr", "script", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    section: ["sectionAttr", "section", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    select: ["selectAttr", "select", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    small: ["smallAttr", "small", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    source: ["sourceAttr", "source", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    span: ["spanAttr", "span", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    strike: ["strikeAttr", "strike", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    strong: ["strongAttr", "strong", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    style: ["styleAttr", "style", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    sub: ["subAttr", "sub", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    summary: ["summaryAttr", "summary", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    sup: ["supAttr", "sup", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    svg: ["svgAttr", "svg", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    table: ["tableAttr", "table", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    tbody: ["tbodyAttr", "tbody", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    td: ["tdAttr", "td", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    template: ["templateAttr", "template", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    textarea: ["textareaAttr", "textarea", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    tfoot: ["tfootAttr", "tfoot", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    th: ["thAttr", "th", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    thead: ["theadAttr", "thead", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    time: ["timeAttr", "time", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    title: ["titleAttr", "title", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    tr: ["trAttr", "tr", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    track: ["trackAttr", "track", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    tt: ["ttAttr", "tt", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    u: ["uAttr", "u", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    ul: ["ulAttr", "ul", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    var: ["varAttr", "var", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    video: ["videoAttr", "video", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"],
    wbr: ["wbrAttr", "wbr", "açıklama", "&lt;! DOCTYPE&gt;", " Note:", "None", "<iframe height='300' style='width: 100%;' scrolling='no' title='Comment' src='https://codepen.io/onepagehtml/embed/qBKOVJm?default-tab=html%2Cresult' frameborder='no' loading='lazy' allowtransparency='true' allowfullscreen='true'>    See the Pen <a href='https://codepen.io/onepagehtml/pen/qBKOVJm'>    Comment</a> by onepagehtml (<a href='https://codepen.io/onepagehtml'>@onepagehtml</a>)    on <a href='https://codepen.io'>CodePen</a>.  </iframe>"]
}
const tagArray = document.getElementsByClassName("tag")
let tagDetailTag = document.getElementById("tagDetails")
for (let j = 0; j < tagArray.length; j++) {
    tagArray[j].addEventListener("click", function () {
        let tagDetailObjItems = tagDetailObj[tagId[j]]
        let tagDetailTemplate = `
        <div class="closebutton" id="cls">
        <i class="fa-solid fa-circle-xmark fa-2x" id="cls"></i>
      </div>
                <div id="${tagDetailObjItems[0]}" class="tagInfo">
                <div class="tagHeader marginT20">${tagDetailObjItems[1]}</div>
                <div class="tagDesc">
                    <div class="tagDectxt marginTRL20">${tagDetailObjItems[2]}</div>
                    <code class="marginT20" style="color: #0e960c">${tagDetailObjItems[3]}</code>
                    <div class="note">${tagDetailObjItems[4]}</div>
                </div>
                <div class="tagAttrs">
                    <div class="attrs">
                        <div class="attrList">
                            <ul class="attrListUl">
                                <h3 class="attrListH">Attributes</h3>
                                <li class="attrListLi" id="test">${tagDetailObjItems[5]}</li>
                            </ul>
                        </div>
                        <div class="attrShow">
                            <iframe class='interactive is-tabbed-shorter-height' height='300vh' width  ='100%' src='https://interactive-examples.mdn.mozilla.net/pages/tabbed/${tagDetailObjItems[1]}.html' title='MDN Web Docs Interactive Example' loading='lazy' data-readystate='complete'></iframe>
                        </div>
                    </div>
                </div>
            </div>
            `
            
        tagDetailTag.innerHTML = tagDetailTemplate
            setTimeout(() => {
                if(document.querySelector("body").textContent.includes("404 Not Found") == true){
                    document.querySelector(".interactive.is-tabbed-shorter-height").remove()
                    console.log("true")
                }
                else{console.log("false")}  
            }, 2000);


        let attrId = this.id
        if (attrId != null && (attrId != undefined) & (attrId != "")) {
            tagDetailTag.style.display = "inline-block";
            let clsbtn = document.getElementById("cls");
            clsbtn.addEventListener("click", () => {
                document.getElementById(`${tagId[j]}` + "Attr").remove()
                tagDetailTag.style.display = "none";
                clsbtn.remove()
            })
        }
    })
}

let sayi 


// let tagDetails = document.getElementById("tagDetails");

// let clsbtn = document.getElementById("cls");
// let attrId, selectTag;
// //CLASS ID - TAGDETAIL DIV
// let items = document.getElementsByClassName("tag");
// for (let i = 0; i < items.length; i++) {
//     //   console.log(items[i]);
//     detailid = tagId[i]
//     items[i].addEventListener("click", function () {
//         attrId = this.id;
//         selectTag = document.getElementById(this.id + "Attr");
//         console.log("attrId = ", attrId, "selectTag", selectTag);
//         // if (attrId != null && (attrId != undefined) & (attrId != "")) {
//         //     tagDetails.style.display = "inline-block";
//         //     selectTag.style.display = "initial";
//         // }
//     });
// }
// CLOSE BUTTON FUNC
// clsbtn.addEventListener("click", function () {
//     tagDetails.style.display = "none";
//     selectTag.style.display = "none";
// });

